mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  profiles:
    active: dev

short-link:
  user-limit:
    time: 1
    max-click: 2
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082
