spring:
  application:
    name: shortlink-admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
            connectTimeout: 5000
            readTimeout: 5000
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  profiles:
    active: dev

logging:
  level:
    com.nageoffer.shortlink.admin.remote.ProjectFeignClient: DEBUG

short-link:
  user-limit:
    time: 1
    max-click: 10
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8000
  address: 127.0.0.1
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082
