locale:
  gaoDe:
    apiKey: e9dc0d95166eccdd3290a2074d406fad
fanfanfan: test0

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: short-link_project-service_stats-save_pg
    topic: short-link_project-service_topic
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: shortlink-project
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # Nacos 地址
        ip: 127.0.0.1
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  short-link:
    domain: fan.ink
    block-domain-list: xiaohongshu.com,weibo.com
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8082
  address: 127.0.0.1
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8088
